//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kyrsah.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excursion
    {
        public Excursion()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public int IdOrder { get; set; }
        public string Name { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public int NumberOfPeople { get; set; }
        public int IdHotelComplex { get; set; }
        public int IdCarrierCompany { get; set; }
        public int IdUser { get; set; }
    
        public virtual CarrierCompany CarrierCompany { get; set; }
        public virtual HotelComplex HotelComplex { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
