//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kyrsah.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelComplex
    {
        public HotelComplex()
        {
            this.Excursion = new HashSet<Excursion>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Nutrition { get; set; }
        public string Rating { get; set; }
    
        public virtual ICollection<Excursion> Excursion { get; set; }
    }
}
