//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kyrsah.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int id { get; set; }
        public int role_id { get; set; }
        public string header { get; set; }
        public string information { get; set; }
        public byte[] news_image { get; set; }
        public System.DateTime news_publication_date { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
