//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kyrsah.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int event_id { get; set; }
        public decimal total_cost { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
